defaults: &defaults
  :log_level: warn
  :mysql:
    :host: localhost
    :user: root
    :password: root 

:development:
  :mysql: 
    :database: development
  <<: *defaults
  :log_level: debug

:test:
  :mysql:
    :database: test
  <<: *defaults

:production:
  :mysql:
    :database: production
  <<: *defaults
